[[pages]]
path = "quotes_recommender/app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "quotes_recommender/ui/preferences.py"
name = "Set Preferences"
icon = "â™¥ï¸"

[[pages]]
path = "quotes_recommender/ui/searching.py"
name = "Search for Quotes"
icon = "ğŸ”"

[[pages]]
path = "quotes_recommender/ui/recommendations.py"
name = "Recommendations"
icon = "ğŸ¤–"
